name:                haskell-craft
version:             0.2.0.0
github:              "Github username here/haskell-craft"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"

#extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/haskell-craft#readme>

dependencies:
  - base
  - vector
  - text
  - HGamer3D (>= 0.9.5 && < 2.0.0)

library:
  source-dirs: src
  dependencies:
    - random

executables:
  haskell-craft:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - haskell-craft
      - base
      - text
      - HGamer3D (>= 0.9.5 && < 2.0.0)

